import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { runStartupTasks } from "@/lib/server-init";
import { ClientInitializer } from "@/components/init-client";
import { SessionProvider } from "next-auth/react";
import ClientProviders from "@/components/utils/ClientProviders";

// Execute server initialization code - runs once on server startup
// This is executed on the server side only
if (typeof window === 'undefined') {
    //console.log('Starting server initialization from root layout...');
    //runStartupTasks()
        //.catch(error => console.error('Failed to run startup tasks:', error));
}

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "`GL Bro`",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ClientProviders> 
                    <ClientInitializer />
                    {children}
                </ClientProviders>
            </body>
        </html>
    );
}
